### ISSUE TITLE
README and code samples out of date

### ISSUE THREAD

**Issue by montyr75** [appsup-dart/firebase#1]
Hey there... Great package! Thanks for building it. It's very useful.

I'm linking to your package in an [article](https://dart.academy/real-time-chat-with-dart-and-firebase/) of mine, so it'd be really great if you could find a few minutes to update the sample code that displays on Pub and the Github page to be current. Looks like the Firebase constructor takes a Uri reference instead of a string now, etc.

Thanks!

**Comment by rbellens** [comment]
Thanks for pointing this out to me (and thanks for the citation).
Should be fixed now.
