### ISSUE TITLE
What is the auth token?

### ISSUE THREAD

**Issue by sethladd** [appsup-dart/firebase#3]
Hi,

I'm trying to use the firebase_rest client (thank you for writing it! :)

What is the auth token (in the Firebase constructor) intended to be? I couldn't find an example, and I need to access a Firebase database that requires auth (or some sort).

Thanks!

**Comment by rbellens** [comment]
The auth token is either the Firebase secret or a JWT token signed with that secret. 
It is comparable with the javascript function Firebase.authWithCustomToken (https://www.firebase.com/docs/web/api/firebase/authwithcustomtoken.html)

**Comment by sethladd** [comment]
Thanks! I'll update the API docs.
