### ISSUE TITLE
consider renaming this repo?

### ISSUE THREAD

**Issue by sethladd** [appsup-dart/firebase#5]
Hi,

What do you think about renaming this report to `firebase_rest.dart` ? It might be easier to find a list of forked repos.

No biggie, just curious. GitHub does maintain redirects, so existing links will continue to work.

**Comment by rbellens** [comment]
Indeed, `firebase_rest` is more logical. The `.dart`extension seems a bit unnecessary (`dart` is already mentioned in the organization name and others don't seem to use it).

**Comment by sethladd** [comment]
Good point.  `firebase_rest` works. Thanks!
